{{ if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "base-chart.fullname" . }}
  labels:
    {{- toYaml .Values.servicemonitor.prometheus.labels | nindent 4 }}
  namespace: {{ .Values.servicemonitor.prometheus.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
    - port: {{ .Values.servicemonitor.port }}
      path: {{ .Values.servicemonitor.path }}
      interval: {{ .Values.servicemonitor.interval }}
{{- end }}
